from .engine import DedupEngine
from .exact_matcher import (
    exact_group,
    keep_first,
    keep_last,
    keep_most_complete,
    keep_by_field,
    KEEP_FIRST,
    KEEP_LAST,
    KEEP_MOST_COMPLETE,
    KEEP_BY_FIELD,
    KEEP_MERGE,
    ALL_KEEP_STRATEGIES,
)
from .exceptions import (
    DedupError,
    InvalidConfigError,
    EmptyMatchKeysError,
    InvalidThresholdError,
    UnknownStrategyError,
    MergeConflictError,
)
from .fuzzy_matcher import (
    UnionFind,
    fuzzy_group,
    fuzzy_match_pairs,
    levenshtein_distance,
    similarity,
)
from .merge_strategies import (
    STRATEGY_FIRST,
    STRATEGY_LAST,
    STRATEGY_LONGEST_STRING,
    STRATEGY_MOST_COMMON,
    STRATEGY_FIRST_NON_EMPTY,
    STRATEGY_CUSTOM,
    ALL_STRATEGIES,
    merge_group,
)
from .min_hash import MinHash, jaccard_similarity, ngram_tokens
from .lsh import MinHashLSH, compute_band_config, LSHBandConfig
from .text_dedup import (
    TextDedupEngine,
    TextDedupCluster,
    TextDedupResult,
    STRATEGY_FIRST as REP_STRATEGY_FIRST,
    STRATEGY_LONGEST as REP_STRATEGY_LONGEST,
    STRATEGY_SHORTEST as REP_STRATEGY_SHORTEST,
    STRATEGY_MIDDLE_LENGTH as REP_STRATEGY_MIDDLE_LENGTH,
    STRATEGY_CUSTOM as REP_STRATEGY_CUSTOM,
    ALL_REPRESENTATIVE_STRATEGIES,
)
from .models import (
    DedupGroup,
    DedupResult,
    FuzzyMatchPair,
    MergeResult,
    Record,
    MergeFunction,
)

__all__ = [
    "DedupEngine",
    "exact_group",
    "keep_first",
    "keep_last",
    "keep_most_complete",
    "keep_by_field",
    "KEEP_FIRST",
    "KEEP_LAST",
    "KEEP_MOST_COMPLETE",
    "KEEP_BY_FIELD",
    "KEEP_MERGE",
    "ALL_KEEP_STRATEGIES",
    "DedupError",
    "InvalidConfigError",
    "EmptyMatchKeysError",
    "InvalidThresholdError",
    "UnknownStrategyError",
    "MergeConflictError",
    "UnionFind",
    "fuzzy_group",
    "fuzzy_match_pairs",
    "levenshtein_distance",
    "similarity",
    "STRATEGY_FIRST",
    "STRATEGY_LAST",
    "STRATEGY_LONGEST_STRING",
    "STRATEGY_MOST_COMMON",
    "STRATEGY_FIRST_NON_EMPTY",
    "STRATEGY_CUSTOM",
    "ALL_STRATEGIES",
    "merge_group",
    "DedupGroup",
    "DedupResult",
    "FuzzyMatchPair",
    "MergeResult",
    "Record",
    "MergeFunction",
    "MinHash",
    "jaccard_similarity",
    "ngram_tokens",
    "MinHashLSH",
    "compute_band_config",
    "LSHBandConfig",
    "TextDedupEngine",
    "TextDedupCluster",
    "TextDedupResult",
    "REP_STRATEGY_FIRST",
    "REP_STRATEGY_LONGEST",
    "REP_STRATEGY_SHORTEST",
    "REP_STRATEGY_MIDDLE_LENGTH",
    "REP_STRATEGY_CUSTOM",
    "ALL_REPRESENTATIVE_STRATEGIES",
]
